### ISSUE TITLE
Add support for browser extensions

### ISSUE THREAD

**Issue by nathancharles** [Netflix-Skunkworks/stethoscope-app#163]
**Note: for support questions, please [email us](mailto:stethoscope@netflix.com) or contact us on [Gitter](https://gitter.im/Netflix-Stethoscope/Lobby)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
There is no ability to check for blocked or required browser extensions.
Given the recent publication of [malicious extensions](https://securitywithsam.com/2019/07/dataspii-leak-via-browser-extensions/) it would be nice to have the ability to look for required or blocked browser extensions.

* **What is the expected behavior?**
Per browser, have the ability to specify extension ids and a requirement state for each, as well as an optional description and installFrom URL.
  - ALWAYS - will result in an error if the extension is not present
  - SUGGESTED - will result in a warning if the extension is not present
  - NOT_SUGGESTED - will result in a warning if the extension is present
  - NEVER - will result in an error if the extension is present

Policy Schema: 
```
browserExtensions:
  chrome:
  - id: extension id
    description: description to be displayed for information on the extension (optional)
    name: extension name (optional)
    installFrom: URL to link user to required extension (optional)
  firefox:
  - id: extension id
    description: description to be displayed for information on the extension (optional)
    name: extension name (optional)
    installFrom: URL to link user to required extension (optional)
  ...
```

* **What is the motivation / use case for changing the behavior?**
To provide a better view and provide remediations into the user's browser extensions.

* **Please tell us about your environment:**

  - Stethoscope Version:
  - Platform:
    - [x] Mac
    - [x] Windows
    - [x] Linux
  - Browser: [Chrome | Firefox | IE | Safari]

[How to find Chrome extensions](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md)
[How to find Firefox extensions](https://askubuntu.com/questions/485786/how-to-show-list-of-installed-extensions-for-firefox-via-command-line)
