### ISSUE TITLE
lastScanTime does not update when /scan is triggered outside of Electron app

### ISSUE THREAD

**Issue by erichs** [Netflix-Skunkworks/stethoscope-app#61]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
If the Origin header is anything other than `stethoscope://main`, the `lastScanTime` field does not update when scans are performed.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Edit `practices/config.yaml` to read:
```yaml
allowHosts:
  - "stethoscope://main"
  - "stethoscope://test"
hostLabels:
  - pattern: "^http://localhost:3000"
    name: Local Server
  - pattern: "^stethoscope://test"
    name: Non-Electron Scan Test
```

2. Start the development server: `yarn start`

3. Wait a minute or so.

4. Exercise the local GraphQL endpoint at `http://localhost:37370/scan`, making sure to set the Origin header to `stethoscope://test`.

* **What is the expected behavior?**
The app should say: `Last scanned by Non-Electron Scan Test a few seconds ago`

Instead, it will read:
`Last scanned by Non-Electron Scan Test a minute ago`

* **Please tell us about your environment:**

  - Stethoscope Version: latest master
  - Platform:
    - [x] Mac
    - [ ] Windows
